### ISSUE TITLE
cloudinary 'Must supply cloud_name' problem

### ISSUE THREAD

**Issue by ahmedbnr** [mastermanav09/ClassZone#77]
Hello @mastermanav09 @Ashish-ash , first of all thank you for your hard work and dedication in making this platform but I have an issue.
I've downloaded your project and set up a cloudinary account with a .env containing all the details, api keys and secrets and everything but i'm encountering the issue of 'Must supply cloud_name' whenever i'm trying to upload a file in create assignment.
this is the error i'm encountering and i'm hoping that you guys can walk me through it.
![image](https://github.com/mastermanav09/ClassZone/assets/48927959/e12b6e90-505a-4d67-b5a3-96299b4c5e46)

**Comment by mastermanav09** [comment]
Hello @ahmedbnr, Thank you for your kind words and for reaching out to us. We appreciate your support and are here to help you with the issue you're facing. Regarding the 'Must supply cloud_name' error, it seems like it is missing from the UPLOAD_CLOUDINARY_URL, we have to specify the cloud_name also in the url itself. Let me know if this works.

Thanks
